### ISSUE TITLE
can not copy *zap.Logger

### ISSUE THREAD

**Issue by romberli** [huandu/go-clone#1]
import (
        clone "github.com/huandu/go-clone"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

func CloneLogger(logger *zap.Logger) *zap.Logger {
	return clone.Clone(logger)
}

it will pacnic with message below:
panic: reflect.Value.Convert: value of type int8 cannot be converted to type zapcore.LevelEnabler

any help is appreciated.

**Comment by huandu** [comment]
Fixed. Thanks for reporting this issue to me.
