### ISSUE TITLE
String 是否始终不应作为标量进行 Clone

### ISSUE THREAD

**Issue by molon** [huandu/go-clone#13]
因为常常会使用类似这样的 `BytesToString` 方法
```
func BytesToString(b []byte) string {
	if len(b) == 0 {
		return ""
	}
	return unsafe.String(&b[0], len(b))
}
```
因为 `go-clone` 在 `!arenaIsEnabled` 的时候会将字符串作为标量处理不进行 `copy`，这样的话，如果对原`Bytes`进行修改了，也会修改掉 `Clone` 后的结果，就很郁闷。(至于为什么会修改原`Bytes`，诸多原因吧，例如我有使用`bytebufferpool`)
```
func TestClone(t *testing.T) {
	b := []byte("hello")
	s := BytesToString(b)
	s2 := gclone.Clone(s)
	b[1] = 'a'
	log.Println(s) // print `hallo`
	log.Println(s2) // pritn `hallo`
}

```
因为`BytesToString`是比较trick的方式，所以`go-clone`默认将字符串当作标量处理也算合理。
但是怎么才能在使用时候根据自身需要修改这个行为呢？

**Comment by huandu** [comment]
我理解你的需求，但是强烈不建议像现在这一样修改 string 的内容，这样做会有潜在的问题。就拿你说的 buffer pool 场景来说，假如在 buffer 回收后，还有 string 指向了这个 buffer，我觉得这应该是业务代码的 bug，相当于过早的释放了内存。

如果实在要实现这个能力，我得重新设计一下接口。我考虑了下，由于现在引入了 `Allocator` 机制，默认的 `Allocator` 是 `heapAllocator`，考虑到可能不同业务场景下有可能内存分配策略不一样，也许需要定制 scalar、opaque pointer、custom func 等各种类型 clone 策略，所以我打算将 `MarkAsScalar`、`MarkAsOpaquePointer`、`SetCustomFunc` 变成 `Allocator` 的方法，全局的这几个函数则是调用 `heapAllocator` 的方法。

**Comment by molon** [comment]
是的，我确实也是因为出现了问题查错才有Clone的需求。
目前的场景是使用`http client`大量请求并且解析返回内容，使用`bytebufferpool`确实能在性能上带来很大的收益，只需要对解析或者抽取的信息进行记录，此时对于一些信息的记录`Clone`就很需要了(例如`regexp`的`FindAllStringSubmatch`内部并不会对原字符串进行`Copy`)。
总的来说，潜在隐患确实是有的，但在部分场景小心处理的话也不会出什么问题收益很可观。

**Comment by huandu** [comment]
现在支持创建一个新的 `Allocator`，在里面将 `string` 标记为非 scalar，从而实现深度拷贝字符串的内容。

例子详见新加的 example，代码如下：

```go
func ExampleAllocator_deepCloneString() {
	// By default, string is considered as scalar and copied by value.
	// In some cases, we may need to clone string deeply, that is, copy the underlying bytes.
	// We can use a custom allocator to do this.
	allocator := NewAllocator(nil, &AllocatorMethods{
		IsScalar: func(t reflect.Kind) bool {
			return t != reflect.String && IsScalar(t)
		},
	})
	cloner := MakeCloner(allocator)

	data := []byte("bytes")
	s1 := *(*string)(unsafe.Pointer(&data)) // Unsafe conversion from []byte to string.
	s2 := Clone(s1).(string)                // s2 shares the same underlying bytes with s1.
	s3 := cloner.Clone(s1).(string)         // s3 has its own underlying bytes.

	copy(data, "magic") // Change the underlying bytes.
	fmt.Println(s1)
	fmt.Println(s2)
	fmt.Println(s3)

	// Output:
	// magic
	// magic
	// bytes
}
```
