### ISSUE TITLE
Help Wanted: Survey of use cases using this package

### ISSUE THREAD

**Issue by huandu** [huandu/go-clone#16]
Hello everyone,

I am the author of this package. I would like to survey how you use this package in your project. Please tell me how you use it, the reason for using it, and the related business scenario.

I want to understand the scope of this package through this survey, so that I can better develop it. My goal is to provide some as efficient as possible memory copy APIs within the scope of Go runtime to meet the memory management needs of various performance-sensitive scenarios. After several years of research and accumulation, especially through the practice of this package, many interesting tricks have proved the plasticity of the memory management related mechanisms in the Go runtime. If I can better understand your usage and requirements, I think I can do a better job of memory copy and management, and make this package more valuable.

Welcome everyone to leave a message below this issue. I will see it and discuss with you.

Thank you!

(P.S. For users who speaks Chinese, please leave your message in #15. Thanks)

**Comment by JuanVargas** [comment]
Hi. Tried top use the package. Unfortunately it did not work for me, not even the example code works.

**Comment by huandu** [comment]
> Hi. Tried top use the package. Unfortunately it did not work for me, not even the example code works.

Can you please open a new issue to provider more information for the bug? I'll investigate it. Thanks.

**Comment by huandu** [comment]
I move the issue to the Discussions #18. Close it.
