### ISSUE TITLE
the same question :orderedmap used List

### ISSUE THREAD

**Issue by xukun311** [huandu/go-clone#4]
hello， when i use ordermap ,i find the same question

// import orderedmap "github.com/wk8/go-ordered-map"

om := orderedmap.New()

om.Set("foo", "bar")

// iterating pairs from oldest to newest:
for pair := om.Oldest(); pair != nil; pair = pair.Next() {
	fmt.Printf("%s => %s\n", pair.Key, pair.Value)
}

newOM := clone.Slowly(om).(*orderedmap.OrderedMap)
for pair := newOM.Oldest(); pair != nil; pair = pair.Next() {
	fmt.Printf("%s => %s\n", pair.Key, pair.Value)
}

**Comment by xukun311** [comment]
#3

**Comment by huandu** [comment]
Thanks for reporting this to me. It's a bug. I find I need to fix this issue thoroughly. The fix will be submitted today.
