### ISSUE TITLE
Build failed on Linux MIPS 32bit

### ISSUE THREAD

**Issue by Loyalsoldier** [huandu/go-clone#6]
I want to deep copy a *tls.Certificate, but build failed on Linux MIPS 32bit(softfloat and hardfloat):

```
../../go/pkg/mod/github.com/huandu/go-clone@v1.2.1/clone.go:280:10: type [2147483647]byte larger than address space
../../go/pkg/mod/github.com/huandu/go-clone@v1.2.1/clone.go:390:11: type [2147483647]byte larger than address space
../../go/pkg/mod/github.com/huandu/go-clone@v1.2.1/clone.go:436:11: type [2147483647]byte larger than address space
```

**Comment by huandu** [comment]
I'm not familiar with MIPS. Per [wikipedia](https://en.wikipedia.org/wiki/MIPS_architecture#Instruction_formats), it seems MIPS 32bit address space is a 26bit value.

I'll submit a new branch to fix this issue. I don't have a MIPS 32bit dev box right now. I need your help to test it. Thanks.

**Comment by Loyalsoldier** [comment]
Just cross compile the code and you'll meet the error.

BTW, I have filed an issue at upstream https://github.com/golang/go/issues/46383

**Comment by huandu** [comment]
I've submitted a fix. Can you please manually test it on your dev box? I tried to cross build it on mips and mipsle. It worked. However, I cannot run `go test` on these archs. I hope to double check this fix before I create a new tag. Thanks.

**Comment by Loyalsoldier** [comment]
Sorry to tell you that I don't have MIPS 32bit devices. 😂

**Comment by huandu** [comment]
OK. I'll tag it anyway. If you find more issues, feel free to open new issue.

**Comment by Loyalsoldier** [comment]
Thanks
