### ISSUE TITLE
Cannot deep copy ECC type tls.Certificate on Go v1.16.4

### ISSUE THREAD

**Issue by Loyalsoldier** [huandu/go-clone#7]
ECC type certificate with error:

```
tls: unsupported certificate curve (P-256)
```

RSA type certificate is ok.

**Comment by huandu** [comment]
Can you please provide a demo to reproduce this issue? It can help me to understand this issue much better. Thanks.

**Comment by Loyalsoldier** [comment]
```go
func deepCopyCert(cert *tls.Certificate) *tls.Certificate {
	return clone.Clone(cert).(*tls.Certificate)
}
```

If to deep copy the certificate(ECC type) and return the new one, it will fail to handshake with error:

```
tls: unsupported certificate curve (P-256)
```

Search the error `tls: unsupported certificate curve` in golang source code, locate to:

https://github.com/golang/go/blob/0410005dc458f23fb15f64354f9a24ca8f2fe044/src/crypto/tls/auth.go#L268-L282

**Comment by huandu** [comment]
The root cause is that package `crypto/tls` validates the curve of a certificate public key by pointer rather than by value. I can mark `elliptic.CurveParams` as scalar to solve this problem.

**Comment by huandu** [comment]
UPDATE: Neither `MarkAsScalar` or `SetCustomFunc` works on pointer types. I cannot use current mechanism to fix this issue. I need to add a new API `MarkAsOpaquePointer` to fix this issue.

**Comment by huandu** [comment]
Tag v1.3.0 is pushed to fix this issue.

**Comment by Loyalsoldier** [comment]
Thanks!
