### ISSUE TITLE
偶发panic: fatal error: found pointer to free object

### ISSUE THREAD

**Issue by jixiuf** [huandu/go-clone#8]
偶发panic:
fatal error: found pointer to free object
 
runtime: marked free object in span 0x7f61bf7566a0, elemsize=16 freeindex=0 (bad use of unsafe.Pointer? try -d=checkptr)

**Comment by huandu** [comment]
能否提供一段可复现问题的代码？如果这方面有困难的话，也请尽可能的提供调用过的 API，比如是否使用了 Wrap 方法之类？

**Comment by jixiuf** [comment]
除了线上环境外 一直没有用简单代码复现出来， 主要用了 Clone 这个方法，其他的没用到 
没有用到Wrap 等，  Clone 的结构体也不太好提供细节， 项目内有10多处用 到了Clone 但究竟是哪处导致的，我一直没调查出来。我们是服务有8个pod 跑24hour 也就偶发4 5 次，我用单测 一直没复现出来 ,但将go-clone 替换成https://github.com/qdm12/reprint 后，这两天没有再出现pannic ,所以bug 应该是go-clone导致的。
![image](https://user-images.githubusercontent.com/461743/158104386-b2047b3d-b9dc-4448-b2dc-e682785626c8.png)

**Comment by jixiuf** [comment]
go的版本是 1.15.15

**Comment by jixiuf** [comment]
![image](https://user-images.githubusercontent.com/461743/158105341-2f3f32dc-1a41-4ac1-adce-a15d3732ccf6.png)
![image](https://user-images.githubusercontent.com/461743/158105618-80e616a9-2ced-429b-885b-41512a59436e.png)
日志比较乱， 贴几x张截图 供你调查，

**Comment by huandu** [comment]
收到，我分析一下。

另外，我想了解下 Clone 的数据结构是否包括一些特殊的数据结构：

- struct type 的 field 是否存在私有字段？
- 是否包含了 sync 包里面的数据结构？
- 是否存在类型为 unsafe.Pointer 的字段？
- 是否存在循环指针，比如在 Clone 一个循环链表？
- 是否存在类型为 interface{} 字段？

这个可以帮助我缩小问题的范围，多谢。

**Comment by jixiuf** [comment]
* struct type 的 field 是否存在私有字段？(无私有字段)
 * 是否包含了 sync 包里面的数据结构？ （不含sync, 纯models层结构，基本对应mysql表结构， ）
 * 是否存在类型为 unsafe.Pointer 的字段？（不含)
 * 是否存在循环指针，比如在 Clone 一个循环链表？(不含，否则早就堆栈溢出了)
 * 是否存在类型为 interface{} 字段？ (简单梳理了下，如果没漏掉的话，应该是不含interface{}的 )
 

好些结构体里用到过以下自定义类型
type Int64 int64
type Int64Slice []int64
type JsonTimestamp time.Time 



有嵌套结构体
有用到time.Time
也有对 如 `[]*Mystruct` 类的slice 进行clone 

我们是用go-clone 做了封装 实现了一个本地缓存库， 大概有42处用到了这个库
存储的数据基本对应了mysql表的数据结构， 也有[]*MyTableStruct 类型的slice

**Comment by huandu** [comment]
我应该找到问题原因了，是因为 GC mark 阶段的时候用 `unsafe.Pointer` 拷贝了指针，无视了 GC 的 write barrier，导致 GC 标记错误最终造成内存多次回收。我现在在本地已经改造了这些拷贝指针的地方，采用了更安全的方法，当前我正在跑一个测试程序验证效果，如果过 24h 还不崩溃，那应该就修复好了。

下面是一段可以稳定复现问题的代码，一般 30s 之内就可以看到崩溃。

```go
package main

import (
	"math"
	"runtime"
	"strconv"
	"sync"
	"time"

	"github.com/huandu/go-clone"
)

func main() {
	type T struct {
		F1 string
	}
	makeTSlice := func(n int) []*T {
		l := n%5 + 1
		slice := make([]*T, 0, l)

		for i := 0; i < l; i++ {
			slice = append(slice, &T{
				F1: strconv.Itoa(n),
			})
		}

		return slice
	}

	max := runtime.GOMAXPROCS(0)
	var wg sync.WaitGroup
	wg.Add(max)

	for i := 0; i < max; i++ {
		go func() {
			defer wg.Done()

			size := 1024
			buffer := make([][]*T, size)

			for n := 0; n < math.MaxInt32; n++ {
				buffer[n%size] = clone.Clone(makeTSlice(n)).([]*T)
			}
		}()
	}

	done := make(chan bool, 1)
	ticker := time.NewTicker(time.Second)

	go func() {
		wg.Wait()
		done <- true
	}()

	for {
		select {
		case <-ticker.C:
			runtime.GC()

		case <-done:
			return
		}
	}
}
```

**Comment by jixiuf** [comment]
多谢，近期会更新验证一下。
